name: firebase_js_interop
description: Wrappers and tools for composing Firebase Cloud Functions in the Dart language
homepage: https://github.com/IO-Design-Team/firebase_js_interop
version: 0.0.1

environment:
  sdk: ^3.3.0

dependencies:
  node_preamble: ^2.0.2
  json_annotation: ^4.9.0

dev_dependencies:
  test: ^1.24.0
  rexios_lints: ^8.0.0

false_secrets:
  - /example/fji_example/android/app/google-services.json
  - /example/fji_example/ios/Runner/GoogleService-Info.plist
  - /example/fji_example/lib/firebase_options.dart
  - /example/fji_example/macos/Runner/GoogleService-Info.plist
