name: firebase_js_interop
description: Wrappers and tools for composing Firebase Cloud Functions in the Dart language
homepage: https://github.com/IO-Design-Team/firebase_js_interop
version: 0.0.5

environment:
  sdk: ^3.3.0

dependencies:
  node_preamble: ^2.0.2
  json_annotation: ^4.9.0
  path: ^1.9.0

dev_dependencies:
  rexios_lints: ^8.1.0

dependency_overrides:
  custom_lint:
    git:
      url: https://github.com/Rexios80/dart_custom_lint
      ref: 6056693aece8cb4f8cbd7e60c9e5996cc21cb190
      path: packages/custom_lint

platforms:
  web:

false_secrets:
  - /example/fji_example/android/app/google-services.json
  - /example/fji_example/ios/Runner/GoogleService-Info.plist
  - /example/fji_example/lib/firebase_options.dart
  - /example/fji_example/macos/Runner/GoogleService-Info.plist
