name: fji_example_core_js_interop
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  fji_example_core:
    path: ../fji_example_core
  firebase_js_interop:
    path: ../../

dev_dependencies:
  rexios_lints: ^8.1.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
