name: fji_example_core_flutter
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fji_example_core:
    path: ../fji_example_core

  json_annotation: ^4.9.0
  cloud_firestore_odm: ^1.0.0-dev.87
  cloud_firestore: ^5.2.1

dev_dependencies:
  rexios_lints: ^8.1.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  cloud_firestore_odm_generator: ^1.0.0-dev.88
