name: fji_example
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0-149.3.beta

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_messaging: ^15.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  rexios_lints: ^8.0.0

flutter:
  uses-material-design: true
